version: 2
jobs:
  build:
    working_directory: /project/workplace/
    docker:
      - image: lakhanmandloi/angular-aws
    branches:
      only:
        - v2
    steps:
      - checkout
      - run:
          name: Install Node
          command: 'curl -sL https://deb.nodesource.com/setup_8.x | bash - && apt-get install -y nodejs'
      - run:
          name: Install Angular CLI
          command: 'npm install -g @angular/cli'
      - type: shell
        command: |
          cd code
          ls
          npm install
          ng -v
          ng build
          aws s3 sync dist/ s3://unite-framework --delete
