version: 2
jobs:
  build:
    working_directory: /project/workplace/
    docker:
      - image: lakhanmandloi/sunbird-ubuntu-fuller
    branches:
      only:
        - v2
    steps:
      - checkout
      - run:
          name: Install Angular CLI
          command: 'npm install -g @angular/cli'
      - type: shell
        command: |
          cd code
          ls
          npm install
          ng -v
          ng build
          aws s3 sync dist/ s3://unite-framework --delete
          
