version: 2
jobs:
  build:
    working_directory: ~/angular-cli-circleci
    docker:
      - image: circleci/node:6-browsers
    branches:
      only:
        - v2
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - type: shell
        command: |
          cd code
          ls
          npm install
          ng -v
          ng build --prod
