version: 2
jobs:
  build:
    working_directory: ~/angular-cli-circleci
    docker:
      - image: circleci/node:6-browsers
    branches:
      only:
        - v2
    steps:
      - checkout
      - type: shell
        command: |
          ls 
          git checkout v2
          ng -v
          node -v
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
