version: 2
jobs:
  build:
    working_directory: ~/angular-cli-circleci
    docker:
      - image: circleci/node:6-browsers
    branches:
      only:
        - v2
    steps:
      - checkout
      - type: shell
        command: |
          cd code
          ls
          sudo npm install @angular/cli
          npm install
          ng -v
          ng build --prod
